apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
      - name: test1
        image: elshabahmed/test:latest
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: test1
spec:
  selector:
    app: test1
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: NodePort
